//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthDays
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthDays()
        {
            this.Symptoms = new HashSet<Symptoms>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public int OverallFeeling { get; set; }
        public string MoodLevel { get; set; }
        public string EnergyLevel { get; set; }
        public string SleepQualityLevel { get; set; }
        public Nullable<decimal> SleepHours { get; set; }
        public string PainLevel { get; set; }
        public string Notes { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Symptoms> Symptoms { get; set; }
    }
}
