//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplProject.pages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptoms
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Severity { get; set; }
        public int HealthDayId { get; set; }
    
        public virtual HealthDays HealthDays { get; set; }
    }
}
